### ISSUE TITLE
Option to set a custom config

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#10]
During the the [Manual run inside Kubernetes via Job #7](#7) it was required to pass a custom config to the app, because as for now it is a single way to configure the application.

We already have some [requests to add configuration options](../issues), but until that is may be useful to have an option to set a custom app config.

Currently we handle that by the [custom entrypoint](../blob/master/docker/docker-entrypoint.sh) and container environment variables
```yaml
        env:
        - name: CONFIG
          value: "/opt/Configuration.cs"
```
