### ISSUE TITLE
Network isolation during tests execution

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#11]
During tests execution, every test is running in its own namespace and for some of them it may be crucial that codex nodes from different tests do not affect each other. 

In Kubernetes we may control network traffic by using [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) which are implemented by the [network plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/).

[DigitalOcean Kubernetes Service](https://docs.digitalocean.com/products/kubernetes/details/features/#vpc-networks) is pre-configured with [Cilium](https://github.com/cilium/cilium/) and supports [network policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/).

Let's test how it works.

We will create 3 areas with the following configuration
 - **area-open** - Allow all Ingress and Egress
 - **area-intra** - Allow all Ingress and Egress, but only in same namespace and DNS/HTTP traffic for node bootstrap and names resolution
 - **area-block** - Block all Ingress and Egress and allow only DNS/HTTP traffic for node bootstrap and names resolution

And in every area we will create the following objects
 - namespace
 - node-1
 - node-2
- service/node-1
- service/node-2
- networkpolicy

### Deploy

 1. Create manifest files
    <details>
    <summary>area-open.yaml</summary>

    ```yaml
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: area-open

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-open-1
      namespace: area-open
      labels:
        name: node-open-1
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-open-2
      namespace: area-open
      labels:
        name: node-open-2
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-open-1
      namespace: area-open
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-open-1
      type: NodePort

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-open-2
      namespace: area-open
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-open-2
      type: NodePort

    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: area-open-allow-any-any
      namespace: area-open
    spec:
      podSelector:
      ingress:
      - {}
      egress:
      - {}
      policyTypes:
      - Ingress
      - Egress
    ```

    </details>

    <details>
    <summary>area-intra.yaml</summary>

    ```yaml
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: area-intra

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-intra-1
      namespace: area-intra
      labels:
        name: node-intra-1
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-intra-2
      namespace: area-intra
      labels:
        name: node-intra-2
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-intra-1
      namespace: area-intra
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-intra-1
      type: NodePort

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-intra-2
      namespace: area-intra
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-intra-2
      type: NodePort

    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: area-intra-allow-ns
      namespace: area-intra
    spec:
      podSelector: {}
      ingress:
      - from:
        - podSelector: {}
      egress:
      - to:
        - podSelector: {}
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
      policyTypes:
      - Ingress
      - Egress
    ```

    </details>

    <details>
    <summary>area-block.yaml</summary>

    ```yaml
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: area-block

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-block-1
      namespace: area-block
      labels:
        name: node-block-1
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-block-2
      namespace: area-block
      labels:
        name: node-block-2
    spec:
      containers:
      - name: doks-debug
        image: digitalocean/doks-debug
        command: ["sh", "-c", "
                 apt update;
                 apt install -y nginx;
                 echo `hostname` >/var/www/html/index.html;
                 nginx -g 'daemon off;'
                 "]
        ports:
        - containerPort: 80

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-block-1
      namespace: area-block
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-block-1
      type: NodePort

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: node-block-2
      namespace: area-block
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        name: node-block-2
      type: NodePort

    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: area-block-any-any
      namespace: area-block
    spec:
      podSelector: {}
      egress:
      - to:
        - podSelector: {}
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
      policyTypes:
      - Ingress
      - Egress
    ```
    </details>

 2. Create objects in Kubernetes
    ```bash
    kubectl apply -f area-open.yaml
    kubectl apply -f area-intra.yaml
    kubectl apply -f area-block.yaml
    ```

### Check

 We performed checks from a separate pod in a default namespace and from pod in every namespace as well

| Source Namespace | Destination Namespace | Connection         |
| ---------------- | --------------------- | ------------------ |
| default          | area-open             | :white_check_mark: |
|                  | area-intra            | :x:                |
|                  | area-blocked          | :x:                |
| area-open        | area-open             | :white_check_mark: |
|                  | area-intra            | :x:                |
|                  | area-blocked          | :x:                |
| area-intra       | area-intra            | :white_check_mark: |
|                  | area-open             | :x:                |
|                  | area-blocked          | :x:                |
| area-blocked     | area-blocked          | :x:                |
|                  | area-open             | :x:                |
|                  | area-intra            | :x:                |

<details>
<summary>details</summary>

> Note: All tests were performed from the first node in the namespace

#### default namespace
```bash
# area-open
curl -m 2 node-open-1.area-open.svc.cluster.local
node-open-1

curl -m 2 node-open-2.area-open.svc.cluster.local
node-open-2

# area-intra
curl -m 2 node-intra-1.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2000 milliseconds

curl -m 2 node-intra-2.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

# area-blocked
curl -m 2 node-block-1.area-block.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-block-2.area-block.svc.cluster.local
curl: (28) Connection timed out after 2000 milliseconds
```

#### area-open namespace

```bash
# area-open - local namespace
curl -m 2 node-open-1.area-open.svc.cluster.local
node-open-1

curl -m 2 node-open-2.area-open.svc.cluster.local
node-open-2

# area-intra
curl -m 2 node-intra-1.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-intra-2.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2004 milliseconds

# area-block
curl -m 2 node-block-1.area-block.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-block-2.area-block.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

# public
curl -m 2 ifconfig.co/country
Netherlands
```

#### area-intra namespace

```bash
# area-intra - local namespace
curl -m 2 node-intra-1.area-intra.svc.cluster.local
node-intra-1

curl -m 2 node-intra-2.area-intra.svc.cluster.local
node-intra-2

# area-open
curl -m 2 node-open-1.area-open.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-open-2.area-open.svc.cluster.local
curl: (28) Connection timed out after 2000 milliseconds

# area-block
curl -m 2 node-open-1.area-open.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-open-2.area-open.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

# public
curl -m 2 ifconfig.co/country
Netherlands
```

#### area-block
```bash
# area-blocked - local namespace
curl -m 2 node-block-1.area-block.svc.cluster.local
node-block-1

curl -m 2 node-block-2.area-block.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

# area-open
curl -m 2 node-open-1.area-open.svc.cluster.local
curl: (28) Connection timed out after 2000 milliseconds

curl -m 2 node-open-2.area-open.svc.cluster.local
curl: (28) Connection timed out after 2000 milliseconds

# area-intra
curl -m 2 node-intra-1.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

curl -m 2 node-intra-2.area-intra.svc.cluster.local
curl: (28) Connection timed out after 2001 milliseconds

# public
curl -m 2 ifconfig.co/country
Netherlands
```
</details>

### Conclusions

 Tests above shows that configured Network Policies works as expected and permits to isolate traffic between pods in different namespaces and between pods in same namespace as well.
