### ISSUE TITLE
Option to authenticate using Service Account

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#18]
As for now, we are using authentication via KubeConfig at tests run.

C# library we use, [support authentication](https://github.com/kubernetes-client/csharp#authenticationconfiguration) using [Service Accounts](https://kubernetes.io/docs/concepts/security/service-accounts/).

It will be very useful to implement such type of authentication which will simplify tests run. Then, we will create a single Service Account which will be specified in the Kubernetes Job manifest and app will use it.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cs-codex-dist-tests
  namespace: cs-codex-dist-tests
  labels:
    name: cs-codex-dist-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      name: cs-codex-dist-tests
    spec:
      serviceAccountName:  cs-codex-dist-tests
      containers:
      - name: cs-codex-dist-tests
        image: codexstorage/cs-codex-dist-tests
        env:
...
```
