### ISSUE TITLE
Create kubeconfig for App

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#21]
Currently, App support authentication with Kubernetes only using kubeconfig.

And to use App in [Remote run](20) mode we need a Service Account with enough permissions and kubeconfig for that.

When [Option to authenticate using Service Account #18](18) will be implemented, we may switch to work with just a Service Account and without kubeconfig. But before that we should create one in same way we did in [Create kubeconfig for GitHub Actions #19](19).

**Comment by veaceslavdoina** [comment]
Manifest for App

<details>
<summary>sa-app.yaml</summary>

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cs-codex-dist-tests

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cs-codex-dist-tests-app
  namespace: cs-codex-dist-tests

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cs-codex-dist-tests-app-role
  namespace: cs-codex-dist-tests
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cs-codex-dist-tests-app-role-binding
  namespace: cs-codex-dist-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cs-codex-dist-tests-app-role
subjects:
  - kind: ServiceAccount
    name: cs-codex-dist-tests-app-sa
    namespace: cs-codex-dist-tests

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cs-codex-dist-tests-app-token
  namespace: cs-codex-dist-tests
  labels:
    name: cs-codex-dist-tests
  annotations:
    kubernetes.io/service-account.name: cs-codex-dist-tests-app-sa
```
</details>

```bash
kubectl apply -f sa-app.yaml
```

Which will create
| Resource             | Name                                   |
| -------------------- | -------------------------------------- |
| `Namespace`          | `cs-codex-dist-tests`                  |
| `ServiceAccount`     | `cs-codex-dist-tests-app-sa`           |
| `ClusterRole`        | `cs-codex-dist-tests-app-role`         |
| `ClusterRoleBinding` | `cs-codex-dist-tests-app-role-binding` |
| `Secret`             | `cs-codex-dist-tests-app-token`        |


It is too open (`"*"`) and we will adjust permissions later when will implement SA creation in Terraform.
