### ISSUE TITLE
Expose metrics during tests execution

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#48]
We already deployed Prometheus in Dist-Tests cluster and tested how we can get Codex metrics.
<details>
<summary>screenshots</summary>

<img width="1431" alt="Screenshot 2023-08-22 at 16 41 15" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/7bd567bb-0cd3-4954-ab23-d40f8cefa7fd">

<img width="1426" alt="Screenshot 2023-08-22 at 17 01 05" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/5c3eb84b-ed79-4bc1-9cd2-f3ea2a238fb2">
</details>

**Configuration**
1. Configure Codex to expose the metrics
2. Expose Codex container metrics port to be accessible for scraping
3. Add Codex Pod annotations to use Prometheus Service Discovery for metrics scraping

**Manifest**
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: codex-metrics
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: codex
    tests-type: dist-tests
spec:
  containers:
  - name: codex
    image: codexstorage/nim-codex:latest-dist-tests
    imagePullPolicy: Always
    env:
    - name: CODEX_METRICS
      value: "true"
    - name: CODEX_METRICS_ADDRESS
      value: "0.0.0.0"
    - name: CODEX_METRICS_PORT
      value: "8008"
    ports:
      - name: metrics
        containerPort: 8008
        protocol: TCP

```
