### ISSUE TITLE
Manual run inside Kubernetes via Job

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#7]
This is a result of the short investigation how we can run dist-tests inside the Kubernetes via Job.

It helps us to understand what we should improve for automatic run inside the Kubernetes via Job and CLI app.

### Now we can do it in the following way
 1. Use a [Docker image](../tree/master/docker) which we may run via Kubernetes Job
 2. Create a separate namespace
 3. Create a secret with kubeconfig
 4. Create a config with the custom settings for the `kubeConfigFile` and `Logging`
 5. Create a Job which will
    - mount secret inside a container
    - mount config inside a container
    - set a variable which will trigger a config owerride from cloned repository with a mounted one
    - mounted config use mounted kubeconfig and logs location

### Deploy

1. Create the following files
    > Note: Please, make sure to update at least *secret.yaml* with the required data

    <details>
    <summary>namespace.yaml</summary>

    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cs-codex-dist-tests
    ```
    </details>

    <details>
    <summary>secret.yaml</summary>

    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: cs-codex-dist-tests
      namespace: cs-codex-dist-tests
      labels:
        name: cs-codex-dist-tests
    stringData:
      kubeconfig.yaml: |
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: ****
            server: ****
          name: ****
        contexts:
        - context:
            cluster: ****
            user: ****
          name: ****
        current-context: ****
        kind: Config
        preferences: {}
        users:
        - name: ****
          user:
            token: ****
    ```
    </details>

    <details>
    <summary>config.yaml</summary>

    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cs-codex-dist-tests
      namespace: cs-codex-dist-tests
      labels:
        name: cs-codex-dist-tests
    data:
      Configuration.cs: |
        using KubernetesWorkflow;

        namespace DistTestCore
        {
            public class Configuration
            {
                public KubernetesWorkflow.Configuration GetK8sConfiguration(ITimeSet timeSet)
                {
                    return new KubernetesWorkflow.Configuration(
                        k8sNamespacePrefix: "ct-",
                        kubeConfigFile: "/opt/kubeconfig.yaml",
                        operationTimeout: timeSet.K8sOperationTimeout(),
                        retryDelay: timeSet.WaitForK8sServiceDelay(),
                        locationMap: new[]
                        {
                            new ConfigurationLocationEntry(Location.BensOldGamingMachine, "worker01"),
                            new ConfigurationLocationEntry(Location.BensLaptop, "worker02"),
                        } 
                    );
                }

                public Logging.LogConfig GetLogConfig()
                {
                    return new Logging.LogConfig("/var/log/cs-codex-dist-tests", debugEnabled: false);
                }

                public string GetFileManagerFolder()
                {
                    return "TestDataFiles";
                }
            }
        }
    ```
    </details>

    <details>
    <summary>job.yaml</summary>

    ```yaml
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: cs-codex-dist-tests
      namespace: cs-codex-dist-tests
      labels:
        name: cs-codex-dist-tests
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: cs-codex-dist-tests
        spec:
          containers:
          - name: cs-codex-dist-tests
            image: codexstorage/cs-codex-dist-tests:sha-300b91e
            env:
            - name: CONFIG
              value: "/opt/Configuration.cs"
            - name: CONFIG_SHOW
              value: "true"
            volumeMounts:
            - name: kubeconfig
              mountPath: /opt/kubeconfig.yaml
              subPath: kubeconfig.yaml
            - name: config
              mountPath: /opt/Configuration.cs
              subPath: Configuration.cs
            - name: logs
              mountPath: /var/log/cs-codex-dist-tests
            # command:
            # - "dotnet"
            # - "test"
            # - "Tests"
          restartPolicy: Never
          volumes:
            - name: kubeconfig
              secret:
                secretName: cs-codex-dist-tests
            - name: config
              configMap:
                name: cs-codex-dist-tests
            - name: logs
              hostPath:
                path: /var/log/cs-codex-dist-tests
    ```

 2. Create resources
    ```bash
    kybectl apply -f namespace.yaml
    kybectl apply -f secret.yaml
    kybectl apply -f config.yaml
    kybectl apply -f job.yaml
    ```

### Results

As a result, Kubernetes will run the Job, which will a run a Pod with app, which will run the dist-tests
```bash
k get jobs -A
NAMESPACE             NAME                  COMPLETIONS   DURATION   AGE
cs-codex-dist-tests   cs-codex-dist-tests   0/1           11m        11m

k get pods -n cs-codex-dist-tests
NAME                        READY   STATUS   RESTARTS   AGE
cs-codex-dist-tests-hmxbm   0/1     Error    0          12m

k get pods -n ct-00009
NAME                        READY   STATUS    RESTARTS   AGE
deploy-0-bfd474648-blnff    2/2     Running   0          8m44s
deploy-1-54557b8686-m2psh   1/1     Running   0          8m41s
```

<details>

<summary>screenshots</summary>
<img width="1362" alt="Screenshot 2023-05-29 at 12 50 04" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/70b9afb9-713e-4881-bf33-7cef1082f664">

<img width="1362" alt="Screenshot 2023-05-29 at 12 51 20" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/04f2b4a4-fb5e-4b28-bf1f-ea75a436548b">

<img width="1358" alt="Screenshot 2023-05-29 at 12 52 23" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/7120bd11-3365-4c4e-9abb-d52b05f24c2f">
</details>

### Improvements proposal
- [ ] Option to set an unique `k8sNamespacePrefix` per tests run
- [ ] Option to set `kubeConfigFile` - now we workaround that with a custom config
- [ ] Option to set `Logging` - now we workaround that with a custom config | #3 
- [ ] Option to set custom config - now we workaround that with a custom entrypoint in the Docker image

**Comment by veaceslavdoina** [comment]
And to handle dynamically Job name
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cs-codex-dist-tests-${NOW}
  namespace: cs-codex-dist-tests
  labels:
    name: cs-codex-dist-tests-${NOW}
    run-id: ${NOW}
```
```
export NOW=$(date +%Y%m%d-%H%M%S) && envsubst < job.yaml | kubectl apply -f -
job.batch/cs-codex-dist-tests-20230602-155944 created

kubectl get jobs -n cs-codex-dist-tests
NAME                                  COMPLETIONS   DURATION   AGE
cs-codex-dist-tests-20230602-155944   0/1           67s        67s
```
